version: "3"
services:
  node:
    container_name: "openelec"
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "80:80"
    command: "node server.js"