version: "3"
services:
  node:
    container_name: "node"
    user: "node"
    build: "."
    command: "node server.js"
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
  mongo:
    container_name: "mongo"
    image: "mongo"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: openelec
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - ./mongo/:/etc/mongo
    expose:
      - "27017"